name: Upload Website

on:
  push:
    branches: [main]

jobs:
  Upload-to-SFTP:
    runs-on: ubuntu-latest

    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm install
      - run: npm run build

      - name: 📂 SFTP uploader
        uses: wangyucode/sftp-upload-action@v1.4.8 # Danke an @https://github.com/wangyucode/sftp-upload-action
        with:
          host: ${{ secrets.ORG_SFTP_HOST }}
          username: ${{ secrets.ORG_SFTP_USERNAME }}
          password: ${{ secrets.ORG_SFTP_PASSWORD }}
          dryRun: false
          forceUpload: true
          localDir: "./dist"
          remoteDir: "/public_html"
          exclude: ".git*,.DS_Store"
